title: Essentials of Machine Learning
description: A comprehensive guide to the fundamentals of machine learning.
show_downloads: False 
google_analytics:
theme: jekyll-theme-cayman

kramdown:
  input: GFM
  math_engine: mathjax # you can also set this field to 'katex'


github:
  is_project_page: false